### ISSUE TITLE
smms官网可以上传，而picgo软件无法上传

### ISSUE THREAD

**Issue by peisencn** [xlzy520/picgo-plugin-smms-user#10]
使用smms图床，无论是picgo默认的上传还是本插件上传都失败，具体配置与日志信息如下，但直接进入smms官网是可以上传的，请问可能是什么问题？

主要是报错信息1出现，有时也出现报错信息2

希望您能帮忙解答，不胜感激

配置文件：
{
  "picBed": {
    "current": "smms",
    "uploader": "smms",
    "smms": {
      "token": "UwkwleZ5YSP1lQHC78egAWeuBJYlXYoh"
    },
    "list": [
      {
        "name": "SM.MS图床",
        "type": "smms",
        "visible": true
      },
      {
        "name": "腾讯云COS",
        "type": "tcyun",
        "visible": false
      },
      {
        "name": "GitHub图床",
        "type": "github",
        "visible": false
      },
      {
        "name": "七牛图床",
        "type": "qiniu",
        "visible": false
      },
      {
        "name": "Imgur图床",
        "type": "imgur",
        "visible": true
      },
      {
        "name": "阿里云OSS",
        "type": "aliyun",
        "visible": false
      },
      {
        "name": "又拍云图床",
        "type": "upyun",
        "visible": false
      },
      {
        "name": "SM.MS-登录用户",
        "type": "smms-user",
        "visible": true
      }
    ],
    "smms-user": {
      "Authorization": "UwkwleZ5YSP1lQHC78egAWeuBJYlXYoh"
    }
  },
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "Ctrl+Shift+U",
        "name": "upload",
        "label": "快捷上传"
      }
    },
    "server": {
      "enable": false,
      "host": "127.0.0.1",
      "port": 36677
    },
    "privacyEnsure": true,
    "showUpdateTip": false,
    "autoStart": true,
    "customLink": "<center> \t<img src=\"$url\" width=\"600\"> </center> <center style=\"font-size:14 px;color:#C0C0C0;\"> $fileName</center>",
    "pasteStyle": "Custom",
    "rename": false,
    "autoRename": true
  },
  "picgoPlugins": {
    "picgo-plugin-smms-user": true
  },
  "debug": true,
  "PICGO_ENV": "GUI",
  "needReload": false
}

报错信息1：
2022-08-18 21:10:15 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: connect ETIMEDOUT 104.21.83.45:443
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 

报错信息2：
2022-08-18 20:21:26 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Program Files\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (C:\Program Files\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by xlzy520** [comment]
@Li0218 看报错都是连接超时，可能跟你网络有关，跟代码逻辑没有关系，除非是接口地址换了

**Comment by xlzy520** [comment]
@Li0218 经过验证，可以确认是这个接口地址被墙了，我给picgo配置代理之后，就能上传了
<img width="644" alt="image" src="https://user-images.githubusercontent.com/28336270/185420442-148c1773-b255-4d3a-9449-511b31e19c6d.png">

**Comment by reed-yang** [comment]
smms官网域名改成了smms.app，与这个有关系吗

**Comment by xlzy520** [comment]
@Reed-yang 登录之后还是https://sm.ms/

**Comment by myheavyhead** [comment]
我也有同样的问题，麻烦能说说具体这么解决吗，代理怎么设置，感谢！
报错信息如下：
2022-08-19 16:14:39 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
    at new RequestError (D:\Work\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Work\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Work\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Work\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (D:\Work\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.onError (D:\Work\PicGo\resources\app.asar\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
-------Error Stack End------- 
2022-08-19 16:15:00 [PicGo INFO] Before transform

**Comment by xlzy520** [comment]
@flower-worm 开启vpn，然后在picgo设置的代理设置里面，配置你的代理端口

**Comment by myheavyhead** [comment]
@xlzy520 您说的这个方法我还是有点没明白，能否加个QQ详聊，如果收费也可以，我qq：295312993

**Comment by myorange2009** [comment]
这个代理怎么设置的，在VPN哪里？
![Quicker_20220827_110439](https://user-images.githubusercontent.com/80094352/187011941-bce3da05-f98b-42e9-bb8f-598d1c7a17d9.png)
还是这个？
![Quicker_20220827_110521](https://user-images.githubusercontent.com/80094352/187011958-64e1dff3-f47f-4239-9e6c-07f54d6bfd64.png)
 图1的设置了不生效

**Comment by xlzy520** [comment]
@myorange2009 
举个例子，你的代理端口好像是19180
<img width="800" alt="image" src="https://user-images.githubusercontent.com/28336270/187016669-cfda1b5f-6c82-4b2a-b67a-836438a8eafa.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/28336270/187016672-8c047941-37b9-46e8-b7f9-984ae3e88c05.png">


这样应该就行了

**Comment by arkr9** [comment]
因为上传的地址改了，把index.js中的url更换成 `https://smms.app/api/v2/upload` 就好了 

![VeryCapture_20220909142611](https://user-images.githubusercontent.com/79648130/189285399-01fd5764-696d-4237-8e2b-5a60ec2dc25d.jpg)

**Comment by xlzy520** [comment]
@arkr9 验证过吗？如果验证过的话，可以提个PR

**Comment by xlzy520** [comment]
由于网络问题，中国大陆用户无法访问 SM.MS，我们添加了备用域名[smms.app](https://smms.app/)。

**Comment by xlzy520** [comment]
@flower-worm @Li0218 @arkr9 @myorange2009 已修改，升级版本即可

**Comment by leland17** [comment]
> @flower-worm @Li0218 @arkr9 @myorange2009 已修改，升级版本即可

![image](https://user-images.githubusercontent.com/9267662/189663687-670d5988-e22a-44d8-9930-e15330ac1c60.png)
似乎smms.app访问还是有超时，看解析出来这个ip地址


![image](https://user-images.githubusercontent.com/9267662/189663997-011a4eb4-d0d9-4b59-a451-381d11a3304c.png)

**Comment by Halcyon666** [comment]
> 

您好 ，请问一下index.js在哪个位置呢？

**Comment by myheavyhead** [comment]
哪个index?&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miracle ***@***.***&gt;; 
发送时间: 2022年11月5日(星期六) 下午2:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xlzy520/picgo-plugin-smms-user] smms官网可以上传，而picgo软件无法上传 (Issue #10)





   
您好 ，请问一下index.js在哪个位置呢？
