### ISSUE TITLE
官网可以上传 APP内无法上传

### ISSUE THREAD

**Issue by WEIFENG2333** [xlzy520/picgo-plugin-smms-user#12]
------Error Stack Begin------
RequestError: Error: connect ETIMEDOUT 59.24.3.174:443
    at new RequestError (C:\Users\weifeng\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\weifeng\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\weifeng\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\weifeng\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.onRequestError (C:\Users\weifeng\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
-------Error Stack End-------

**Comment by xlzy520** [comment]
@WEIFENG2333 是否使用了VPN进官网

**Comment by xlzy520** [comment]
https://github.com/xlzy520/picgo-plugin-smms-user/issues/10
相同反馈

**Comment by xlzy520** [comment]
@WEIFENG2333 已修改，升级版本即可
